# These are supported funding model platforms

github: # eldzejgm, eldzejgm, eldzejgm, eldzejgm
patreon: # EldzejGM
open_collective: # EldzejGM
ko_fi: # EldzejGM
tidelift: # npm/babel
community_bridge: # EldzejGM
liberapay: # ~1772820
issuehunt: # EldzejGM
otechie: # EldzejGM
custom: # ["https://github.com/eldzejgm", "https://github.com/eldzejgm", "https://github.com/eldzejgm", "https://github.com/eldzejgm"]
